# Generated by Django 4.1.5 on 2023-01-17 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(help_text='coupon code', max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='discount amount of a product', max_digits=10)),
                ('coupon_start_date', models.DateTimeField(auto_now_add=True)),
                ('coupon_end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_title',
            field=models.CharField(help_text='brand name', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(help_text='category name', max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(help_text='product code', max_length=100)),
                ('product_name', models.CharField(help_text='name of product', max_length=100)),
                ('product_price', models.IntegerField(help_text='price of product', max_length=10)),
                ('stock_in', models.IntegerField(help_text='product stocked in the shop', max_length=10)),
                ('stock_out', models.IntegerField(help_text='amount of product sell from the shop', max_length=10)),
                ('product_availability', models.IntegerField(help_text='amount of available product', max_length=10)),
                ('product_description', models.TextField(help_text='description of products')),
                ('brand', models.ForeignKey(help_text=' brand name of a product', on_delete=django.db.models.deletion.CASCADE, to='shop_app.brand')),
                ('category', models.ForeignKey(help_text=' category of the product', on_delete=django.db.models.deletion.CASCADE, to='shop_app.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.IntegerField(help_text='amount of products want to order', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='product prices', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='total prices of products', max_digits=10)),
                ('user_id', models.ForeignKey(help_text=' user id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.IntegerField(help_text='amount of product want to buy', max_length=10)),
                ('product_id', models.ForeignKey(help_text='product id', on_delete=django.db.models.deletion.CASCADE, to='shop_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
