# Generated by Django 4.1.5 on 2023-01-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_coupon_alter_brand_brand_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(help_text='amount of product want to buy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_availability',
            field=models.IntegerField(help_text='amount of available product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(help_text='price of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_in',
            field=models.IntegerField(help_text='product stocked in the shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_out',
            field=models.IntegerField(help_text='amount of product sell from the shop'),
        ),
    ]
