# Generated by Django 4.1.5 on 2023-01-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_cart_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(help_text='amount of products want to order'),
        ),
    ]
