# Generated by Django 4.1.5 on 2023-01-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, help_text='price of product', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_out',
            field=models.IntegerField(blank=True, help_text='amount of product sell from the shop', null=True),
        ),
    ]
