# Generated by Django 4.1.5 on 2023-01-17 04:59

from django.db import migrations, models
import systems.enums


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_product_product_price_alter_product_stock_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[(1, 'AMOUNT'), (2, 'PERCENTAGE')], default=systems.enums.DiscountType['AMOUNT'], max_length=10),
        ),
    ]
