# Generated by Django 4.1.5 on 2023-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_coupon_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[(1, 'AMOUNT'), (2, 'PERCENTAGE')], default=1, max_length=10),
        ),
    ]
