# Generated by Django 4.1.5 on 2023-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_coupon_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_start_date',
            field=models.DateTimeField(),
        ),
    ]
