# Generated by Django 4.1.5 on 2023-01-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_alter_coupon_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
