# Generated by Django 4.1.5 on 2023-01-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_cart_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
