# Generated by Django 4.1.5 on 2023-01-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_rename_product_id_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
    ]
