# Generated by Django 4.1.5 on 2023-01-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
