# Generated by Django 4.1.5 on 2023-01-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_rename_products_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
    ]
