# Generated by Django 4.1.5 on 2023-01-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_rename_product_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='total_quantity',
        ),
    ]
