# Generated by Django 4.1.5 on 2023-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_rename_quantity_order_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='House Number of user', max_length=500)),
                ('upazila', models.TextField(help_text=' Upazila name of the user')),
                ('district', models.TextField(help_text='District name of the user')),
                ('division', models.TextField(help_text='Division name of the user')),
                ('contact_no', models.IntegerField(help_text='user mobile number')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
