# Generated by Django 4.1.5 on 2023-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='address of the of user', max_length=500),
        ),
    ]
