# Generated by Django 4.1.5 on 2023-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'SHIPPING_ADDRESS'), ('billing', 'BILLING_ADDRESS')], default='shipping', max_length=10),
        ),
    ]
